welcome:
  message: Welcome to Product-Microservice from GIT. Actuator refresh! 
  allProductsUrl: http://localhost:8085/inventory/allProducts
  productsByNameUrl: http://localhost:8085/inventory/productByName/
  productByIdUrl: http://localhost:8085/inventory/product/
