welcome:
  message: Welcome to Product-Microservice from GIT. 
  allProductsUrl: http://localhost:8085/inventory/allProducts
  productByName: http://localhost:8085/inventory/productByName/
  productById: http://localhost:8085/inventory/product/
